# .github/FUNDING.yml

github: [jinto-ag] # Your GitHub username for GitHub Sponsors
patreon: # your-patreon-username (if you create one)
open_collective: # your-project-name (good for community projects)
ko_fi: jinto_ag # Replace with your Ko-fi username
tidelift: # pypi/jinpy-utils (if you join Tidelift)
community_bridge: # Leave empty unless you have a Linux Foundation project
liberapay: jinto-ag # Your Liberapay username
issuehunt: # Leave empty unless you want bug bounties
lfx_crowdfunding: # Leave empty unless you have a Linux Foundation project
polar: "jinto-ag" # New platform, leave empty for now
buy_me_a_coffee: jintoag # Your Buy Me a Coffee username
thanks_dev: # Leave empty unless you use this platform
